---
- hosts: all
  tasks:
    - name: Run DISM via cmd - Check features installed
      register: dism_features
      ansible.windows.win_command:
        argv:
        - cmd.exe
        - /c
        - dism.exe
        - /online
        - /get-features
        - /format:table
    - debug:
        msg: "{{ dism_features.stdout_lines|list }}"
        #msg: "{{ dism_features.stdout_lines | list | regex_findall('^.NetFx$', multiline=True, ignorecase=True) }}"