---
- hosts: all
  tasks:
    - name: Enable dotNET3 via DISM - use Verbose 3
      ansible.windows.win_command:
        cmd: '"C:\Windows\system32\dism.exe" "/online" "/enable-feature" "/featureName:NetFx3"' 
    - name: Reboot a machine that takes time to settle after being booted
      ansible.windows.win_reboot:
        post_reboot_delay: 10