---
- hosts: all
  tasks:
    - name: Run DISM via cmd - Check features installed - use Verbose 3
      ansible.windows.win_command:
        argv:
        - cmd.exe
        - /c
        - dism.exe
        - /online
        - /get-features
        - /format:table
        register: dism_features
    - debug:
        msg: "{{ dism_features.stdout_lines|list }}"