---
  - name: running command in Windows
    hosts: all
    tasks:
      - name: Execute the dir command
        ansible.windows.win_command: dir
        register: dirout
        
      - debug:
          var: dirout.stdout_lines
