---
- hosts: all
  tasks:
    - name: Enable dotNET4 via DISM - use Verbose 3
      ansible.windows.win_command:
        cmd: '"C:\Windows\system32\dism.exe" "/enable-feature" "/featureName:NetFx4" "/all"'
