---
- hosts: all
  tasks:
  - name: Remove dotNet3
    ansible.windows.win_feature:
      name:
      - NetFx3
      state: absent
  - name: Reboot if installing Web-Server feature requires it
    ansible.windows.win_reboot:
    when: win_feature.reboot_required    