---
  - name: running command in Windows
    hosts: all
    tasks:
      - name: Execute the dir command
        register: dirout
        ansible.windows.win_command:
          cmd: dir
      - debug:
          var: dirout.stdout_lines