---
- hosts: all
  tasks:
  - name: Run a command under a non-Powershell interpreter (cmd in this case)
    ansible.windows.win_shell: echo %HOMEDIR%
    args:
      executable: cmd
    register: homedir_out
